import type { ContextBundle } from '@ipcg/shared';
export const seedBundle: ContextBundle = {
  generatedAt: '2026-01-01T00:00:00.000Z',
  version: 'seed',
  disclaimers: [
    'This project provides public and derived contextual datasets only.',
    'It does not provide official findings, legal opinions, engineering assessments, causation conclusions, safety determinations, or recommendations.',
    'Any interpretation generated by users or third-party AI tools is external to this project.'
  ],
  datasets: [
    { id:'data-gov-ie-catalog', title:'Ireland Open Data Portal catalogue', publisher:'Department of Public Expenditure, NDP Delivery and Reform', domains:['local-government','public-services','transport','environment','planning','health','education','economy'], sourceUrl:'https://data.gov.ie/', license:'Varies per dataset', updateCadence:'continuous', geography:'Ireland', temporalCoverage:'varies', formats:['CKAN API','CSV','GeoJSON','JSON','XML'], description:'Master catalogue used to discover and track public Irish datasets and publisher metadata.', resources:[], provenanceNotes:['Use CKAN metadata as discovery layer, not as proof of dataset quality.'] },
    { id:'cso-statbank', title:'CSO StatBank and statistical geography', publisher:'Central Statistics Office Ireland', domains:['demographics','economy','housing','local-government'], sourceUrl:'https://data.cso.ie/', license:'CSO open data terms; verify per table', updateCadence:'periodic', geography:'Ireland', temporalCoverage:'varies', formats:['PX','CSV','API','JSON'], description:'Population, labour, housing, commuting and statistical-area context.', resources:[], provenanceNotes:['Keep table IDs and retrieval timestamps for every normalized extract.'] },
    { id:'nta-gtfs', title:'NTA GTFS and public transport data', publisher:'National Transport Authority', domains:['transport','infrastructure'], sourceUrl:'https://www.transportforireland.ie/transitData/PT_Data.html', license:'NTA open-data terms; verify current terms', updateCadence:'frequent', geography:'Ireland', temporalCoverage:'current schedules/realtime where available', formats:['GTFS','GTFS-RT','CSV'], description:'Stops, routes, trips, schedules and realtime public-transport context.', resources:[], provenanceNotes:['Realtime snapshots must be timestamped and retained only according to permitted terms.'] },
    { id:'rsa-collisions', title:'RSA collision and casualty data', publisher:'Road Safety Authority / Department of Transport', domains:['collisions','roads','transport'], sourceUrl:'https://www.rsa.ie/road-safety/statistics', license:'Verify source and reuse terms', updateCadence:'periodic', geography:'Ireland', temporalCoverage:'historic', formats:['Tableau','CSV','API if available'], description:'Collision and casualty records and aggregates used as one context domain.', resources:[], provenanceNotes:['No blackspot, fault, causation or recommendation claims are produced by this project.'] }
  ],
  entities: [
    { id:'country:ie', type:'country', name:'Ireland', datasetIds:['cso-statbank'], properties:{ iso2:'IE' } },
    { id:'catalog:data-gov-ie', type:'catalog', name:'data.gov.ie', datasetIds:['data-gov-ie-catalog'], properties:{ endpoint:'https://data.gov.ie/api/3/action/package_search' } },
    { id:'domain:transport', type:'domain', name:'transport', datasetIds:['data-gov-ie-catalog'], properties:{} },
    { id:'dataset:nta-gtfs', type:'dataset', name:'NTA GTFS and public transport data', datasetIds:['nta-gtfs'], properties:{} }
  ],
  relationships: [
    { id:'rel:nta-domain-transport', subject:'dataset:nta-gtfs', predicate:'belongs_to_domain', object:'domain:transport', datasetIds:['nta-gtfs'], confidence:'source' },
    { id:'rel:catalog-country', subject:'catalog:data-gov-ie', predicate:'indexes_public_data_for', object:'country:ie', datasetIds:['data-gov-ie-catalog'], confidence:'source' }
  ],
  observations: [
    { id:'obs:seed-dataset-count', entityId:'country:ie', metric:'seed_dataset_count', value:4, unit:'datasets', datasetId:'data-gov-ie-catalog' }
  ],
  sourceRecords: []
};
