import { z } from 'zod';
export const DatasetDomain = z.enum(['transport','roads','collisions','planning','environment','weather','demographics','health','education','public-services','infrastructure','economy','local-government','housing','energy','culture']);
export type DatasetDomain = z.infer<typeof DatasetDomain>;
export const Resource = z.object({ id:z.string(), datasetId:z.string(), name:z.string(), format:z.string(), url:z.string().optional(), description:z.string().optional(), lastModified:z.string().optional(), size:z.number().optional(), mimetype:z.string().optional() });
export type Resource = z.infer<typeof Resource>;
export const Dataset = z.object({ id:z.string(), title:z.string(), publisher:z.string(), publisherId:z.string().optional(), domains:z.array(DatasetDomain), sourceUrl:z.string().url(), license:z.string(), updateCadence:z.string(), geography:z.string(), temporalCoverage:z.string(), formats:z.array(z.string()), description:z.string(), resources:z.array(Resource).default([]), metadataModified:z.string().optional(), provenanceNotes:z.array(z.string()).default([]), quality:z.object({ hasResources:z.boolean(), hasOpenLicense:z.boolean(), hasMachineReadableResource:z.boolean(), resourceCount:z.number(), formatCount:z.number() }).optional() });
export type Dataset = z.infer<typeof Dataset>;
export const Entity = z.object({ id:z.string(), type:z.string(), name:z.string(), datasetIds:z.array(z.string()), geometry:z.object({ type:z.string(), coordinates:z.unknown() }).optional(), properties:z.record(z.unknown()).default({}) });
export type Entity = z.infer<typeof Entity>;
export const Relationship = z.object({ id:z.string(), subject:z.string(), predicate:z.string(), object:z.string(), datasetIds:z.array(z.string()), confidence:z.enum(['source','derived-high','derived-medium','derived-low']), validFrom:z.string().optional(), validTo:z.string().optional(), evidence:z.string().optional() });
export type Relationship = z.infer<typeof Relationship>;
export const Observation = z.object({ id:z.string(), entityId:z.string(), metric:z.string(), value:z.union([z.string(), z.number(), z.boolean()]), unit:z.string().optional(), timeStart:z.string().optional(), timeEnd:z.string().optional(), datasetId:z.string(), sourceRecordId:z.string().optional() });
export type Observation = z.infer<typeof Observation>;
export const SourceRecord = z.object({ id:z.string(), datasetId:z.string(), publisher:z.string(), sourceUrl:z.string(), license:z.string(), retrievedAt:z.string(), metadataModified:z.string().optional(), resourceCount:z.number(), formats:z.array(z.string()), resourceUrls:z.array(z.string()).default([]), provenanceNotes:z.array(z.string()).default([]) });
export type SourceRecord = z.infer<typeof SourceRecord>;
export const CoverageReport = z.object({ generatedAt:z.string(), datasetCount:z.number(), publisherCount:z.number(), domainCounts:z.record(z.number()), formatCounts:z.record(z.number()), licenseCounts:z.record(z.number()), quality:z.object({ withResources:z.number(), withMachineReadableResources:z.number(), withOpenLicense:z.number(), withoutResources:z.number() }), missingness:z.array(z.object({ scope:z.string(), note:z.string(), impact:z.string() })) });
export type CoverageReport = z.infer<typeof CoverageReport>;
export const ContextBundle = z.object({ generatedAt:z.string(), version:z.string(), datasets:z.array(Dataset), entities:z.array(Entity), relationships:z.array(Relationship), observations:z.array(Observation), sourceRecords:z.array(SourceRecord).default([]), coverage:CoverageReport.optional(), disclaimers:z.array(z.string()) });
export type ContextBundle = z.infer<typeof ContextBundle>;
export const CLAIM_BOUNDARY = [
  'This project provides public and derived contextual datasets only.',
  'It does not provide official findings, legal opinions, engineering assessments, causation conclusions, safety determinations, or recommendations.',
  'Any interpretation generated by users or third-party AI tools is external to this project.'
] as const;
export function normalizeSearch(value: string): string { return value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, ''); }
export function slug(value: string): string { return normalizeSearch(value).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 96) || 'unknown'; }
export const MACHINE_READABLE_FORMATS = new Set(['csv','json','geojson','xml','xlsx','xls','zip','api','kml','kmz','shp','gpkg','wms','wfs','rdf','ttl','parquet','geoparquet']);
